/* ─────────────────────────────────────────────
   BLOG DATA — 21 posts (representing the 70)
───────────────────────────────────────────── */
export const POSTS = [
  { id: 21, slug: "personal-website-lethal-2026", title: "What Makes a Personal Website Lethal in 2026", excerpt: "A no-fluff, research-backed breakdown of every design, performance, branding, and technical dimension that separates forgettable from unforgettable.", category: "Tech", readTime: "25 min", date: "Feb 27, 2026", demand: 99, featured: true, tags: ["Web Design","Performance","Personal Brand","GEO"], published: true },
  { id: 1, slug: "ai-powered-business-2026", title: "How to Build an AI-Powered Business in 2026 — The No-Fluff Playbook", excerpt: "Which AI tools are producing real revenue, which business models work (SaaS, agent-as-a-service, AI-augmented freelancing), and what the real moats are.", category: "AI", readTime: "18 min", date: "Feb 20, 2026", demand: 98, featured: true, tags: ["Business Models","Tool Stack","Moat Analysis","Revenue"], published: true },
  { id: 2, slug: "death-of-seo-geo-2026", title: "The Death of Traditional SEO — And What Replaces It in the AI Search Era", excerpt: "Google's AI Overviews have tanked organic traffic. Generative Engine Optimization (GEO) is the successor framework every website owner must understand now.", category: "Tech", readTime: "14 min", date: "Feb 18, 2026", demand: 96, featured: true, tags: ["GEO","SEO","Traffic","AI Search"], published: false },
  { id: 3, slug: "200k-tech-job-2026", title: "How to Land a $200K+ Tech Job in 2026 — The Exact Playbook", excerpt: "Which roles survived AI displacement with salaries intact, which companies are hiring, and what the negotiation math looks like for total comp.", category: "Career", readTime: "16 min", date: "Feb 15, 2026", demand: 96, featured: true, tags: ["Salary","Hiring","Levels.fyi","Negotiation"], published: true },
  { id: 4, slug: "agentic-ai-era", title: "The Agentic AI Era: What It Means for Your Job, Business, and Life", excerpt: "Autonomous AI systems that plan, execute, and iterate without human direction — the most disruptive technical development of the decade, explained clearly.", category: "AI", readTime: "15 min", date: "Feb 12, 2026", demand: 95, featured: false, tags: ["Agents","Automation","Future","Jobs"], published: false },
  { id: 5, slug: "one-person-million-business", title: "Building a One-Person $1M Business — The Model Map for Solopreneurs", excerpt: "AI tools make what once required 5–10 people possible for one. The specific business models where solo operators hit $1M in 2026.", category: "Business", readTime: "17 min", date: "Feb 10, 2026", demand: 95, featured: false, tags: ["Solopreneur","Revenue","AI Stack","Systems"], published: false },
  { id: 6, slug: "rag-systems-guide", title: "Building RAG Systems That Actually Work — A Developer's Definitive Guide", excerpt: "RAG is the dominant architecture for enterprise AI. But naive implementations fail in production. Here's the full engineering stack — from chunking to GraphRAG.", category: "AI", readTime: "22 min", date: "Feb 8, 2026", demand: 94, featured: false, tags: ["RAG","Vector DB","LLM","Production"], published: false },
  { id: 7, slug: "psychology-of-money", title: "The Psychology of Money — Why Smart People Make Terrible Financial Decisions", excerpt: "Loss aversion, present bias, anchoring, and the endowment effect — the specific mental traps that cost people money and the system designs that override them.", category: "Money", readTime: "13 min", date: "Feb 5, 2026", demand: 94, featured: false, tags: ["Behavioral Finance","Investing","Kahneman","Systems"], published: false },
  { id: 8, slug: "product-market-fit-bible", title: "The Product-Market Fit Bible — How to Know If You Have It", excerpt: "Sean Ellis' 40% rule, retention curve analysis, the Superhuman PMF framework — making the most important startup concept actually measurable.", category: "Business", readTime: "15 min", date: "Feb 3, 2026", demand: 94, featured: false, tags: ["PMF","Startups","Retention","Metrics"], published: false },
  { id: 9, slug: "salary-negotiation-science", title: "How to Negotiate Your Salary — The Science and Scripts for Getting What You're Worth", excerpt: "The average person who negotiates earns $1M more over their career. 68% never negotiate. Here are the exact scripts that work.", category: "Career", readTime: "12 min", date: "Jan 30, 2026", demand: 96, featured: false, tags: ["Negotiation","Salary","Scripts","BATNA"], published: false },
  { id: 10, slug: "micro-saas-guide-2026", title: "The Complete Guide to Building and Selling a Micro-SaaS in 2026", excerpt: "Niche identification, validation specific to SaaS, solo growth strategies, and what Micro-SaaS acquisitions look like in 2026 with real multiples.", category: "Business", readTime: "19 min", date: "Jan 27, 2026", demand: 93, featured: false, tags: ["SaaS","Acquisition","Niche","Exit"], published: false },
  { id: 11, slug: "ai-healthcare-2026", title: "AI in Healthcare — What's Real, What's Coming, and What the Data Shows", excerpt: "FDA-cleared AI medical tools, where AI is genuinely outperforming clinicians, where it's still unreliable, and what patients and professionals should actually know.", category: "AI", readTime: "16 min", date: "Jan 24, 2026", demand: 93, featured: false, tags: ["Healthcare","FDA","Clinical AI","Ethics"], published: false },
  { id: 12, slug: "founder-financial-handbook", title: "The Founder's Financial Handbook — From $0 to First $1M", excerpt: "Unit economics, burn rate, payback period, MRR targets by milestone — the specific numbers that gate each stage of growth. No motivational fluff.", category: "Money", readTime: "20 min", date: "Jan 22, 2026", demand: 90, featured: false, tags: ["Unit Economics","Burn Rate","MRR","YC Data"], published: false },
  { id: 13, slug: "software-engineering-2026", title: "Software Engineering in 2026 — Skills That Still Matter When AI Writes the Code", excerpt: "GitHub Copilot writes 40% of production code. Stack Overflow traffic is collapsing. Is the developer still relevant? Data-backed answer.", category: "Career", readTime: "14 min", date: "Jan 19, 2026", demand: 97, featured: false, tags: ["Developer","AI Coding","Career","Skills"], published: false },
  { id: 14, slug: "mit-admissions-real-data", title: "How to Get Into MIT, Stanford, or Top-5 CS — The Real Data", excerpt: "What the acceptance rates actually mean, what distinguishes admitted students beyond GPA, and the specific project types that appear in accepted profiles.", category: "Career", readTime: "18 min", date: "Jan 16, 2026", demand: 92, featured: false, tags: ["MIT","Admissions","CS","Applications"], published: false },
  { id: 15, slug: "deepfakes-2026", title: "Deepfakes in 2026 — The Technology, the Threats, the Detection, and the Law", excerpt: "CEO fraud costing millions, election interference, non-consensual imagery — documented 2025–2026 incidents with detection rates and protection guides.", category: "AI", readTime: "15 min", date: "Jan 13, 2026", demand: 90, featured: false, tags: ["Deepfakes","Security","Law","Detection"], published: false },
  { id: 16, slug: "vc-demystified", title: "Venture Capital Demystified — How Funding Really Works From Seed to IPO", excerpt: "Term sheet anatomy, dilution math, SAFE vs. priced rounds — the intelligence briefing first-generation founders never got but legacy-connected founders walk in with.", category: "Money", readTime: "21 min", date: "Jan 10, 2026", demand: 88, featured: false, tags: ["VC","Term Sheets","SAFE","Dilution"], published: false },
  { id: 17, slug: "personal-brand-2026", title: "How to Build a Personal Brand That Prints Opportunities in 2026", excerpt: "The 2026 personal brand stack: platform strategy, content architecture, the specific credibility framework, and how to measure brand ROI.", category: "Business", readTime: "13 min", date: "Jan 7, 2026", demand: 91, featured: false, tags: ["Personal Brand","Content","LinkedIn","Trust"], published: false },
  { id: 18, slug: "africa-tech-ecosystem-2026", title: "Africa's Tech Ecosystem in 2026 — The Investment Map and Opportunity Ceiling", excerpt: "1.4 billion people, median age 19, highest mobile-first adoption globally. Yet VC funding dropped 40%. What the numbers actually show.", category: "Business", readTime: "17 min", date: "Jan 4, 2026", demand: 82, featured: false, tags: ["Africa","Lagos","Nairobi","Fintech"], published: false },
  { id: 19, slug: "deep-work-science-2026", title: "The Science of Deep Work in 2026 — How Top Performers Weaponize Focus", excerpt: "AI handles shallow tasks. Human judgment and creativity are what remain scarce. Current neuroscience of attention + the protocols high performers use.", category: "Health", readTime: "12 min", date: "Dec 30, 2025", demand: 90, featured: false, tags: ["Focus","Neuroscience","Productivity","Systems"], published: false },
  { id: 20, slug: "self-taught-dev-roadmap", title: "The Self-Taught Developer Roadmap in 2026 — From Zero to Employed", excerpt: "The honest, current, fastest path from zero to employed — which language to start, the portfolio projects that pass the thinking test, and the job search strategy.", category: "Career", readTime: "16 min", date: "Dec 27, 2025", demand: 95, featured: false, tags: ["Self-Taught","Roadmap","Portfolio","Jobs"], published: false },
];

export const CATEGORIES = ["All", "AI", "Business", "Tech", "Money", "Career", "Health", "Society"];
